* Corrected the branch for shared_dguk_assets
* Solved problem with creating synced_folder with user co and related
  permission problem doing pip install of the ckan source. Uses the
  answer from Sean Burlington:
  http://stackoverflow.com/questions/17966365/vagrant-chicken-and-egg-shared-folder-with-uid-apache-user

* In the Puppetfile:
  Rename module "solr"->"datagovuk/solr" to avoid warning:
    Invalid module name 'solr', you should qualify it with
    'ORGANIZATION-solr' for resolution to work correctly

* In the README:
  * in the Vagrant install, do git_clone_all.sh before vagrant up.
  * in the Vagrant install, no need to install ruby/librarian separately
  * Specify librarian-puppet version 1.0.3 because using latest (1.1)
  leads to error:
      ERROR:  Error installing librarian-puppet:
      "activesupport requires Ruby version >= 1.9.3."
    (see https://github.com/purple52/librarian-puppet-vagrant/issues/12 )